//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTA.DeviceEmulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev")]
        public string DefaultEnvironment {
            get {
                return ((string)(this["DefaultEnvironment"]));
            }
            set {
                this["DefaultEnvironment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("global.azure-devices-provisioning.net")]
        public string DeviceProvisioningServiceEndpoint {
            get {
                return ((string)(this["DeviceProvisioningServiceEndpoint"]));
            }
            set {
                this["DeviceProvisioningServiceEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>dev=0ne00064748</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DeviceProvisioningServiceIdScopeMap {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeviceProvisioningServiceIdScopeMap"]));
            }
            set {
                this["DeviceProvisioningServiceIdScopeMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Certificates")]
        public string CertificatesFolder {
            get {
                return ((string)(this["CertificatesFolder"]));
            }
            set {
                this["CertificatesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>dev=8B7C5620292D04DB01D55A60EB797F587AFC1620</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RootCertificateThumbprintMap {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RootCertificateThumbprintMap"]));
            }
            set {
                this["RootCertificateThumbprintMap"] = value;
            }
        }
    }
}
